<?php

namespace CodeHack\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseRequirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRequirementRepository extends EntityRepository
{
}
