<?php

namespace CodeHack\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmergencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmergencyRepository extends EntityRepository
{
}
