<?php

namespace CodeHack\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmergencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmergencyRepository extends EntityRepository
{
  
  public function getPeopleList($id)
    {  
      $privacy= $this->getEntityManager()
              ->createQuery(" SELECT * FROM CodeHack\CoreBundle\Entity\Privacy p
                JOIN Smammas\UserBundle\Entity\User u
                WITH p.user_id = u.id
                WHERE u.id = :id")
              ->setParameter('id', $id)
              ->getResult();
     if (count($privacy) > 0)
       return true;
     return false;
    }
  
}
